### ISSUE TITLE
Application version should be stored  as assembly information.

### ISSUE THREAD

**Issue by marcin-sucharski** [marcin-waszak/glossary#3]
Currently version is stored as Form1 field. It should be stored as assembly version property (described here: https://msdn.microsoft.com/en-us/library/eyw13ks6(v=vs.110).aspx )

Edit: There is mismatch between:
https://github.com/marcin-waszak/glossary/blob/master/glossary/Properties/AssemblyInfo.cs#L35
and
https://github.com/marcin-waszak/glossary/blob/master/glossary/Form1.cs#L17

**Comment by marcin-waszak** [comment]
Solved, thank you
